### ISSUE TITLE
Unable to install asciidoc-bootstrap-docs-backend

### ISSUE THREAD

**Issue by aftabhafeez** [mojavelinux/asciidoc-bootstrap-docs-backend#7]
Hi @mojavelinux ,@

I am unable to install asciidoc-bootstrap-docs-backend by the following command and getting an error "asciidoctor: FAILED: missing converter for backend 'install'" 

asciidoctor --backend install "D:\asciidoc\bootstrap-4.5.0.zip" 

Error Details:

Traceback (most recent call last):
        13: from C:/Ruby25-x64/bin/asciidoctor:23:in `<main>'
        12: from C:/Ruby25-x64/bin/asciidoctor:23:in `load'
        11: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/bin/asciidoctor:14:in `<top (required)>'
        10: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
         9: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:112:in `each'
         8: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
         7: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `convert_file'
         6: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `open'
         5: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `block in convert_file'
         4: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1479:in `convert'
         3: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1367:in `load'
         2: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1367:in `new'
         1: from C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:490:in `initialize'
C:/Users/aftab.hafeez/.gem/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1083:in `update_backend_attributes': asciidoctor: FAILED: missing converter for backend 'install'. Processing aborted. (NotImplementedError)

Could you please advise how to resolve this issue.

**Comment by mojavelinux** [comment]
This repository has nothing to do with Asciidoctor. It was created long before Asciidoctor ever existed. It's for AsciiDoc Py.

There is no bootstrap integration for Asciidoctor, to my knowledge. If you are still using AsciiDoc Py, then you might be interested in https://github.com/llaville/asciidoc-bootstrap-backend, which is a newer version of this code. But I don't have experience with it myself.

**Comment by aftabhafeez** [comment]
Thanks for your reply.
